all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
    prod:
      vars:
        env: prod
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
 
      hosts:
        centos2:
          ansible_host: centos2
          hostname: centos2
        debian1:
          ansible_host: debian1
          hostname: debian1
